version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: docker/app/dev.Dockerfile
    environment:
      - MIX_ENV=test
      - APP_HOST=localhost
    depends_on:
      - database

  database:
    image: postgres:11.4-alpine
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
