version: '3.7'

services:
  app:
    environment:
      - MIX_ENV=test
    depends_on:
      - database

  database:
    image: postgres:11.4-alpine
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
