version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    environment:
      - APP_SECRET=${APP_SECRET}
      - DATABASE_PORT=5432
      - DATABASE_HOST=database
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - './app:/usr/src/app'
    ports:
      - '80:8080'
    depends_on:
      - database

  database:
    image: postgres:10.5
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}

